### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Im-Kayun** [renzuzu/renzu_garage#318]
Car keys should be fixed items, as they should not disappear when you put the cars away. I did some tests regarding the keys and you can lock and unlock the car without having them in the inventory, the same thing happens with the car ignition, sometimes it starts without us having the key. It would make sense to check if the player has the key in the inventory when the car turns on/off and lock/unlock. If a player took the car with the engine running, he could continue driving because it was as if the keys were there, he just couldn't turn it off and lock/unlock it.
Why is it that in the private garage I can get inside the car and press E to exit and in the public garage I can't?

**Comment by renzuzu** [comment]
>Car keys should be fixed items, as they should not disappear when you put the cars away
this will overload player inventory if they use too many vehicle.

> I did some tests regarding the keys and you can lock and unlock the car without having them in the inventory, the same thing happens with the car ignition, sometimes it starts without us having the key. 

i need reproduction on this as its works well on my end.

my steps is. get a car in garage. and drop the key and try to start or lock/unlock.

>Why is it that in the private garage I can get inside the car and press E to exit and in the public garage I can't?
in my test , its because the vehicle is all lock.
maybe we could unlock all vehicle in public garage (garage area goto garage)

**Comment by Im-Kayun** [comment]
With the ox inventory it is possible to create items that function as stash, for example key rings where players could store their keys. Maybe add an option in the config to choose between these 2 ways?
Tomorrow I record the video

**Comment by Im-Kayun** [comment]
The problem of locking the car without keys may have been my mistake as I was also using qb-vehiclekeys.
Regarding the car starting without the keys, it happens few times but I was able to record it. 
https://streamable.com/bi8fq4
I also noticed that the lock/unlock animation gets bugged when you are moving.
https://streamable.com/ybxuxu

**Comment by renzuzu** [comment]
it seems the Wait(1000) is the issue on first video.

![image](https://user-images.githubusercontent.com/82306584/203566926-972e3752-7e8e-487a-95a5-614e5670ba7d.png)

anything else it could be the gamepool is not seeing the vehicle or its  have a lower population type < 4 or the state bags are not updating real time.

and second issue most likely a mistake on animation flags

![image](https://user-images.githubusercontent.com/82306584/203567619-e1a9c5c1-a1d1-4103-98c5-1437a231f19c.png)

49 is the correct i assume

thank for keep helping to improve the resource. im gonna look on your other open issues about garage keys

**Comment by Im-Kayun** [comment]
ox_inventory already has this feature
![image](https://user-images.githubusercontent.com/84230221/203576197-27839858-f727-43da-ab66-15065fbd5c87.png)

**Comment by renzuzu** [comment]
you want to use one of those containers?

there is no export to create containers atm. i dont know why overextended team does not add it.is it because they want developers does not rely too much on other resource feature.

**Comment by Im-Kayun** [comment]
i think using those is fine. since you only need to define the key holder item since all of them will only accept keys. but if there is a better way, it's up to you.

**Comment by renzuzu** [comment]
a stash is probably the best option. with hooks. so only keys are able to deposit.

the question is where to put the stash point.
maybe in gotogarage? theres a drawer there. we can create a stash point. and this only wll work on ox_inventory or qb-inventory.

as the container i dont know what logic to implement that way.
so everytime player gets a vehicle they will receive item container for keys if they dont have it.
it will be confusing for player i think.

**Comment by Im-Kayun** [comment]
no, the key holder is just a container item that works as a container and is used to organize the keys in the inventory, so you don't have to have all the keys scattered around if they are permanent and don't disappear when you put the vehicle away

**Comment by renzuzu** [comment]
i have made it as optional. as most of server owner have not the same idea as you have.

**Comment by Im-Kayun** [comment]
thanks, just one more doubt I have. If I use another dealership script, is there an event or export to give the car key to the player when he buys it?

**Comment by renzuzu** [comment]
>is there an event or export to give the car key to the player when he buys it?

theres a export for giving vehicle keys via server.

exports.renzu_garage:GiveVehicleKey(plate,source)

>if I don't have the keys I get them. I think that the keys should only be given when the player buys the car and in x amount so that the player can give keys to teammates so they can use the car as well. 

this is the default behavior of resource.
the keys are from garage not dealership
i could create a config for this so there will be no keys when you spawn a vehicle from garage.

>would have to change the lock if he's the owner, with that x more keys would be given and the old keys would no longer work.

this is not possible in the current logic.
but its not hard to implement i just need to setup a metadata serial for each vehicle.
so the item metadata can have serials.

> It should also only be possible to store and take out the car from the garage if you have the keys in inventory.

this mean if you dont have the vehicle keys. you will not able to take out the vehicle, right?
i dont know if this is good idea because if some developer just switched to this garage. and all old vehicle will be not able to take out, without manualy creating keys or using the duplication key system from legion square garage.
i dont think that is user friendly for players. im trying to make this user friendly for dev and players.
and beside this required slightly overhaul of the resource logic, i can do it but i dont know if its worth it.

>In this case, if a friend had one of the car keys, he could keep it in his garage.

this is not possible in the current logic as the vehicle ownership from server requires identifier.
you could store it if you borrow the vehicle from friend. but not able to take it out again.

the garage keys is the same logic of this but its required you to have garage keys when having a borrowed vehicle.

**Comment by Im-Kayun** [comment]
Right maybe a command that reads all the cars from the database and gives the keys to their owners? Like ox_inventory does with items.
For example, I have my car and my friend and I have the keys, when he stored the vehicle in his garage it would come out of mine.
The car is still associated with me in terms of ID, but it is in my friend's possession because it is in his garage

**Comment by Im-Kayun** [comment]
sounds good to me, but it would only be in the garage where it was kept

**Comment by Im-Kayun** [comment]
I just sent the link to the script to give you an idea of how it worked. Not for you to use the code, besides your garages logic is different and wouldn't fit. 

Ok, when you have time you'll update, thanks

**Comment by renzuzu** [comment]
your right, logic is different, thank you. ill sort it out this tonight
