### ISSUE TITLE
Quick question about Config.PlateSpace

### ISSUE THREAD

**Issue by BlueSky-fur** [renzuzu/renzu_garage#44]
So what exactly does `Config.PlateSpace` do? 

Also, what exactly does this mean? `Config.ReturnPayment`

Is this some sort of "you get money for returning your car" thing?

**Comment by renzuzu** [comment]
plate space allow you to remove all space or ignored'

some people do use CUSTOMPLATE like "KING"
if you use with spaces, the plate will save to database with "   KING   " instead of "KING"

and about return payment thats the payment required if you lost you vehicle somewhere, or if vehicle is not in the garage
its like asking a delivery for your car.

**Comment by BlueSky-fur** [comment]
Ahh, thank you for the quick and detailed answer!
